### ISSUE TITLE
Plugin to monitor Aruba Instant On Switch 1830

### ISSUE THREAD

**Issue by saharawolf** [centreon/centreon-plugins#4115] opened 2022-12-19 15:33 UTC
Hi, 
I am lookink to monitor Aruba Instant On Switch 1830 via SNMP. I tried with the HPE standard abd Aruba Standard without success. 
Is there another plugin that could help ?

Regards

**Comment by garnier-quentin** [comment] 2022-12-27 08:44
Have you tried the hp procurve plugin ?

**Comment by saharawolf** [comment] 2022-12-28 10:29
hi, 

Yes i have already tried, it gives error: UNKNOWN: SNMP GET Request : Cant get a single value.

regards

**Comment by garnier-quentin** [comment] 2022-12-28 10:33
You can provide a full snmpwalk of following branch: .1.3.6.1.4.1

**Comment by joschi99** [comment] 2023-02-16 11:33
Have same problem on Intant One switch 1930

snmpwalk: 
[InstantOn_1960.zip](https://github.com/centreon/centreon-plugins/files/10755407/InstantOn_1960.zip)

MIB: 
[1960_MIBs_2.7.0.103.zip](https://github.com/centreon/centreon-plugins/files/10755408/1960_MIBs_2.7.0.103.zip)

**Comment by garnier-quentin** [comment] 2023-02-16 12:05
The snmpwalk is incomplete.

**Comment by lucie-dubrunfaut** [comment] 2024-06-17 14:07
Hello :)

Recently one of our consultants reported a similar issue to us with this plugin. At this moment we have not fully isolate if the issue is occurring with certain equipments or if the MIB (and consequently the OIDs) has been reworked.
In his case using the [plugin AOSCX](https://github.com/centreon/centreon-plugins/blob/develop/src/network/aruba/aoscx/snmp/plugin.pm) works better because his equipment was on `.47196` OID (corresponding to the OIDs check in Aruba AOSCX plugin) and not on `.14823` (corresponding to the OIDs check in Aruba standard plugin).

Feel free to give us an .snmpwalk anonymized (full snmpwalk of enterprise branch :snmpwalk -ObentU -v 2c -c public address .1.3.6.1.4.1 > equipment.snmpwalk) to help us with troubleshooting this issue. And also if you have MIB information to help us re-synchronize the rights OIDs it can helps a lot.
Thanks for your patience 🙏

**Comment by joschi99** [comment] 2024-06-19 04:04
I have just attached a full snmpwalk on Feb 23 on this issue, you can find there the walk and the mib file.
I don't think that for this issue the aoscx plugin will work, because the corrisponding snmp oid is not existing on this product family.

**Comment by lucie-dubrunfaut** [comment] 2024-06-19 09:00
Hello :)

I asked you again for another snmpwalk because Quentin said the same day that this snmpwalk is incomplete. I've opened it and there is no `.14823` to match with the OIDs used in the [standard Aruba plugin](https://github.com/search?q=repo%3Acentreon%2Fcentreon-plugins+path%3A%2F%5Esrc%5C%2Fcentreon%5C%2Fcommon%5C%2Faruba%5C%2Fsnmp%5C%2Fmode%5C%2F%2F++14823&type=code).

**Comment by joschi99** [comment] 2024-06-24 07:16
I have done a check on a Aruba 1830, there is no enterprise ID `.14823` or` .47196` available.

**Comment by lucie-dubrunfaut** [comment] 2024-06-24 07:29
Hello,

Ok here is the pain point I think on Aruba 1830 the standard plugin is not relevant, we may need to create another way to monitor Aruba 1830. This will need an SNMPwalk, a MIB file and ideally the modes wanted. Also this will require a TheWatch idea to be voted on [here](https://thewatch.centreon.com/ideas).

**Comment by joschi99** [comment] 2024-06-25 05:09
Hi @lucie-dubrunfaut,

there are just 2 topics for them on the watch
- https://thewatch.centreon.com/platform-7/get-cpu-on-aruba-switch-1930-or-2530-error-unknown-snmp-table-request-cant-get-a-single-value-1419?tid=1419&fid=7
- https://thewatch.centreon.com/platform-7/what-custom-template-can-i-use-for-an-aruba-1930-24g-poe-switch-2813?tid=2813&fid=7

Should I open another one?

**Comment by lucie-dubrunfaut** [comment] 2024-06-25 06:56
Hello :) @joschi99 

At this moment I'm not sure if Aruba Switch 1830 and 1930 will match on the same OIDs and consequently can be monitored with the same plugin. Moreover this two topics are questions and not ideas so they can't be vote on to engage the development process. But you can quote them in your idea topic and I can let them a word also to invite them for voting on the idea topic.

**Comment by joschi99** [comment] 2024-06-26 05:52
We have access to both device families (18xx, 19xx), but our impression is that both are responding similar and have same problem that actually we cannot monitor hardware, cpu, memory. What do you need to understand better the problem?

**Comment by lucie-dubrunfaut** [comment] 2024-06-26 07:11
Ok it's a good start point, in theory I have snmpwalk for both devices and we will have more visibility about this when development team start the ticket corresponding to this enhancement. I close this issue (it is linked in the development ticket anyway), can you create an idea TheWatch to vote on [here](https://thewatch.centreon.com/ideas) please?

**Closed by lucie-dubrunfaut** 2024-06-26 07:11 UTC
Labels: question
