### ISSUE TITLE
Varnish App Uptime  Throws all counters in 0

### ISSUE THREAD

**Issue by fmonpelat** [centreon/centreon-plugins#534] opened 2016-11-09 14:50 UTC
Hi, we are executing the script as below, but we have to pass the commands: "-1 -f MAIN.* |sed -e "s/MAIN.//g" " to varnishstat to make uptime work. is this ok? maybe we could add a new option to select "MAIN" or others.
Please keep in mind I do not understand varnish all that well.

Cheers,
`
perl centreon_plugins.pl --plugin=apps::varnish::local::plugin --remote --hostname=xxxxx --ssh-option='-l=_MonitoreoSSH' --mode=sessions
OK: Session herd: 0.00, Session Read Ahead: 0.00, Session Linger: 0.00, Session Closed: 0.00, Session Pipeline: 0.00 | 'sess_herd'=0.00;;;; 'sess_readahead'=0.00;;;; 'sess_linger'=0.00;;;; 'sess_closed'=0.00;;;; 'sess_pipeline'=0.00;;;;
`
and the one that works:
`
perl centreon_plugins.pl --plugin=apps::varnish::local::plugin --remote --hostname=xxxxx --ssh-option='-l=_MonitoreoSSH' --mode=sessions --command-options='-1 -f MAIN.* |sed -e "s/MAIN.//g"'
OK: Session Linger: 0.00, Session Read Ahead: 0.00, Session Closed: 1461794.71, Session herd: 174.71, Session Pipeline: 0.00 | 'sess_linger'=0.00;;;; 'sess_readahead'=0.00;;;; 'sess_closed'=1461794.71;;;; 'sess_herd'=174.71;;;; 'sess_pipeline'=0.00;;;;
`
Facundo.

**Comment by Sims24** [comment] 2016-11-15 12:24
Hello @fmonpelat 

Could you please copy/paste here or send me an email with the result of the following command on the varnish server : 

/usr/bin/varnishstat -1 2>&1

Thanks,

**Comment by fmonpelat** [comment] 2016-11-15 17:00
Hi @Sims24 
Sent you an email with the command execution (/usr/bin/varnishstat -1 2>&1).

Thanks to you.

**Comment by Sims24** [comment] 2016-11-16 08:19
Thanks, I'll take a look asap and let you know.

**Comment by Sims24** [comment] 2016-11-17 19:15
@fmonpelat , wow looks like output change quite a lot since this mode has been developped =)  What version of varnish are you using actually ?  

I reproduced the issue and I feel like values are increasing even if I do not modify my input, are the value seems ok to you ? 

Need to talk to @garnier-quentin , to have its mind. We can probably just do some tweaks on the regexp, but I think this mode need a larger refactoring. 

An interesting thing would be to  have an absolute and per second what do you think ? Many thing possible but I'm a little bit lost when I look at https://pathfinder.kly.no/html/varnishstat.html =)

I'll do some work on it asap and ping you to test. 
Thx

**Comment by Sims24** [comment] 2016-11-18 09:31
@florian-asche available to talk about this ?

**Comment by Sims24** [comment] 2016-11-20 16:53
Linked with https://github.com/centreon/centreon-plugins/issues/370

**Comment by fmonpelat** [comment] 2016-11-29 13:45
sorry for the delay, this is my version:

varnishstat (varnish-4.0.3 revision b8c4a34)
Copyright (c) 2006 Verdens Gang AS
Copyright (c) 2006-2014 Varnish Software AS

So its merged ok, thanks.

**Comment by Sims24** [comment] 2016-12-01 10:05
@fmonpelat, no problem ! 

Just to be sure on how it works, it would be great if you could play "/usr/bin/varnishstat -1 2>&1" 3 times with a delay of 30 sec between commands and send it by mail :)

We'll probably have huge refactoring here.

Thanks,

**Comment by Sims24** [comment] 2017-05-18 12:53
Hi, 

Coming back on this. Will fix in next few days (really this time ;)). 

Closing this one and follow up on #370 . 

Thanks

**Closed by Sims24** 2017-05-18 12:53 UTC
Labels: enhancement
