### ISSUE TITLE
UNKNOWN: Host 'YYY-YYY-YYYYY.zzzzzz.tld' : overall status is gray

### ISSUE THREAD

**Issue by lscotti-itmed** [centreon/centreon-plugins#2948] opened 2021-07-07 12:02 UTC
Hello guys,

I've an issue using centreon_vmware_connector_client.pl to query several ESXi checks.

The plugin return "Host 'YYY-YYY-YYYYY.zzzzzz.tld' : status connected, overall status is gray", I don't understand why.
How can I debug this ?

```
[root@XXX-XXX-XX ~]# /usr/lib/centreon/plugins//centreon_vmware_connector_client.pl --plugin=apps::vmware::connector::plugin --mode=status-host --custommode=connector --connector-hostname='localhost' --connector-port='5700' --container='YYY-YYY-YYYYY-1'  --esx-hostname='YYY-YYY-YYYYY.zzzzzz.tld' --unknown-status='%{status} !~ /^connected$/i' --warning-status='' --critical-status='' --unknown-overall-status='%{overall_status} =~ /gray/i' --warning-overall-status='%{overall_status} =~ /yellow/i' --critical-overall-status='%{overall_status} =~ /red/i' --verbose
UNKNOWN: Host 'YYY-YYY-YYYYY.zzzzzz.tld : overall status is gray |
Host 'YYY-YYY-YYYYY.zzzzzz.tld' : status connected, overall status is gray
```

Packages version:
```
[root@XXX-XXX-XX ~]# /usr/lib/centreon/plugins//centreon_vmware_connector_client.pl --version
Global Version: 20201211 (e7080cf6d) 

[root@XXX-XXX-XX ~]# rpm -qa | grep -i VMWARE2-connector
centreon-plugin-Virtualization-Vmware2-Connector-Plugin-20201211-091649.el7.centos.noarch
```

**Comment by garnier-quentin** [comment] 2021-07-07 12:03
Is it a standalone ESX ?

**Comment by lscotti-itmed** [comment] 2021-07-07 12:05
> Is it a standalone ESX ?

It is part of a vCenter but I query every ESXi, I don't query from the vCenter

**Comment by garnier-quentin** [comment] 2021-07-07 12:06
I think you can only that status if you query from the vcenter.

**Comment by lscotti-itmed** [comment] 2021-07-07 12:09
> I think you can only that status if you query from the vcenter.

How to be sure?

**Comment by garnier-quentin** [comment] 2021-07-07 12:10
Query the same host from the vcenter

**Comment by UrBnW** [comment] 2021-07-22 08:59
Same "issue", querying host overall status through vCenter returns yellow.
Querying the yellow host directly returns :
`UNKNOWN: Host 'my-nice-host' : overall status is gray`

Works as designed ? Issue ? Bug-report to VMware ?

Thx 👍

**Comment by garnier-quentin** [comment] 2021-07-22 09:01
It's by design for me. It's not a vmware issue.

**Comment by lscotti-itmed** [comment] 2021-07-22 09:04
By design?
Shouldn't it work the same when querying the host or the vcenter?

**Comment by UrBnW** [comment] 2021-07-22 09:05
In my example [above](https://github.com/centreon/centreon-plugins/issues/2948#issuecomment-884757938), as the vCenter, the host interface itself properly returns a yellow flag, so I wonder why it would not work :

![Screenshot 2021-07-22 at 11 01 58](https://user-images.githubusercontent.com/40244829/126614803-1b31078c-4625-4a21-b5d7-18fdd974ed03.png)

But I'm not sure how it works internally :)

**Comment by UrBnW** [comment] 2021-07-22 13:57
Note that requesting a standalone yellow ESX returns the following :
`Host 'my-standalone-host' : status connected, overall status is gray`

![Screenshot 2021-07-22 at 15 44 38](https://user-images.githubusercontent.com/40244829/126649466-6767f205-d677-47b6-8fb4-9f001d92ce93.png)

About `connectionState` :
https://vdc-download.vmware.com/vmwb-repository/dcr-public/da47f910-60ac-438b-8b9b-6122f4d14524/16b7274a-bf8b-4b4c-a05e-746f2aa93c8c/doc/vim.HostSystem.ConnectionState.html
_connected	: Connected to the server. For ESX Server, this is always the setting._

So, it's clear that some host related items should be monitored through the vCenter only.

**Comment by garnier-quentin** [comment] 2021-07-29 12:41
Thanks for detailed informations @UrBnW . We can close it

**Closed by garnier-quentin** 2021-07-29 12:41 UTC
Labels: question
