### ISSUE TITLE
[cloud::kubernetes::plugin] error 404 when it list the cronjobs

### ISSUE THREAD

**Issue by FreshardF** [centreon/centreon-plugins#4713] opened 2023-10-24 07:49 UTC
Hello,

I think than the uri for api cronjob have change in GCP kubernetes (GKE).

old uri : /apis/batch/v1beta1/cronjobs

new uri : /apis/batch/v1/cronjobs

test:
beta uri :
curl -H "Authorization: Bearer <TOKEN>" -H "Accept: application/json" 
-H "User-Agent: centreon::plugins::backend::http::useragent" 
https://TTT.PPP.YYYY.XXX:443**/apis/batch/v1beta1/cronjobs**?limit=100 -k

{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"the server could not find the requested resource","reason":"NotFound","details":{},"code":**404**}

no beta uri :
curl -H "Authorization: Bearer <TOKEN>" -H "Accept: application/json" 
-H "User-Agent: centreon::plugins::backend::http::useragent" 
https://TTT.PPP.YYYY.XXX:443**/apis/batch/v1/cronjobs**?limit=100 -k

{"kind":"CronJobList","apiVersion":"batch/v1","metadata":{"resourceVersion":"142751960"},"items":[]}

**Comment by Emanuel-Bourel** [comment] 2024-05-30 09:29
Good morning,

the problem is still present on the version Global Version: 20240411 (e7bf805) of the centreon_kubernetes_api.pl plugins.

So I modified the line    8774
 url_path => $self->{namespace} ne '' ? '/apis/batch/v1beta1/namespaces/' . $self->{namespace} . '/cronjobs': '/apis/batch/v1beta1/cronjobs'

in 

url_path => $self->{namespace} ne '' ? '/apis/batch/v1/namespaces/' . $self->{namespace} . '/cronjobs': '/apis/batch/v1/cronjobs'

can you support this modification?
Regards

**Comment by lucie-dubrunfaut** [comment] 2024-07-02 12:31
Hello :)

This issue is at this moment supported by this PR https://github.com/centreon/centreon-plugins/pull/5026/files could you confirm it to me? I'll close it when the PR will be integrated (it's planned in the coming weeks)

**Comment by lucie-dubrunfaut** [comment] 2024-08-26 09:19
Hello :)

This issue was resolved with the August release and the following PR: https://github.com/centreon/centreon-plugins/pull/5109

**Closed by lucie-dubrunfaut** 2024-08-26 09:19 UTC
Labels: bug
