### ISSUE TITLE
[network::cisco::wlc::snmp::plugin]  --mode=radius-auth-servers: wrong unit

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#5000] opened 2024-04-29 14:39 UTC
Monitoring authentication servers the unit returned is not ms, but µs:
![image](https://github.com/centreon/centreon-plugins/assets/6400595/3ecfbffb-c3fc-4f0e-bc48-64a4927ce024)

Please corret the plugin to show the right unit and also the thresholds input.

Same issue also on accounting servers

**Comment by lucie-dubrunfaut** [comment] 2024-07-18 14:16
Hello :)

The issue is taken into account, also could you provide us an anonymized SNMPWalk to write the associated tests when correcting the bug?

**Comment by joschi99** [comment] 2024-07-29 05:00
Send to you by mail

**Comment by lucie-dubrunfaut** [comment] 2024-11-07 11:14
Hello :)

Could you test if this dev fix it ? https://github.com/centreon/centreon-plugins/pull/5277

**Comment by lucie-dubrunfaut** [comment] 2024-12-12 11:23
Hello :)

This issue should be resolved with release 24.11, so let me close it.

**Closed by lucie-dubrunfaut** 2024-12-12 11:23 UTC
Labels: bug, in-backlog
