### ISSUE TITLE
Unknown option: warning-total at /usr/lib/centreon/plugins/centreon_as400_connector_client.pl line 141.

### ISSUE THREAD

**Issue by doudz** [centreon/centreon-plugins#3831] opened 2022-08-12 07:19 UTC
Trying to monitor message queues on AS400 I got the following error

Unknown option: warning-total at /usr/lib/centreon/plugins/centreon_as400_connector_client.pl line 141.

The command used is :
`/usr/lib/centreon/plugins/centreon_as400_connector_client.pl --plugin=os::as400::connector::plugin --mode=message-queue --connector-hostname='localhost' --connector-port='8091' --connector-proto='http' --as400-hostname=**** --as400-username='***' --as400-password='***' --message-queue-path='QBATCH' --filter-message-id='' --min-severity='' --max-severity='' --warning-total='' --critical-total='' --display-messages --memory --verbose`

but  looking the help commande I found that --warning-total and --critical-total don't exist, it's --warning-messages and --critical-messages
`/usr/lib/centreon/plugins/centreon_as400_connector_client.pl  --plugin=os::as400::connector::plugin --mode=message-queue --help
`

```
Mode:
    Check message queue.

    --message-queue-path
            Specify the message queue (Required. Eg:
            --message-queue-path='/QSYS.LIB/QSYSOPR.MSGQ').

    --memory
            Check only new messages.

    --filter-message-id
            Filter messages by id (can be a regexp).

    --min-severity
            Filter messages with severity greater than or equal to X.

    --max-severity
            Filter messages with severity less than to X.

    --display-messages
            Display messages in verbose output.

    --warning-messages --critical-messages
            Thresholds.
```

**Comment by Sims24** [comment] 2022-08-12 07:25
Hi, 

This is not a bug of centreon-plugins but rather the packaging on top of it. 

We will fix this. 

Thanks,

**Comment by garnier-quentin** [comment] 2022-08-12 11:13
It will be fixed in september release

**Closed by garnier-quentin** 2022-08-12 11:13 UTC
Labels: bug, in-backlog
