### ISSUE TITLE
[os::linux::snmp::plugin] update help

### ISSUE THREAD

**Issue by lpinsivy** [centreon/centreon-plugins#1180] opened 2018-10-18 13:33 UTC
Related to https://github.com/centreon/centreon/issues/6639

Help indicates --warning & --critical

**Comment by LLFT** [comment] 2018-10-22 12:14
Hi,

Thank you for the transfer in the right section.

The problem is not so much on the help but on the plugin itself and its CPU mode.

```
/usr/lib/centreon/plugins/centreon_linux_snmp.pl --plugin=os::linux::snmp::plugin  --version
Plugin Version: 0.1
/usr/lib/centreon/plugins/centreon_linux_snmp.pl --plugin=os::linux::snmp::plugin --mode=cpu --version
Mode Version: 1.0
```

this plugin does not mention the simple "warning" anywhere.
The problem is the same for Windows


I let you look for yourself :

`/usr/lib/centreon/plugins/centreon_linux_snmp.pl --plugin=os::windows::snmp::plugin --mode=cpu --help`

or

`/usr/lib/centreon/plugins/centreon_linux_snmp.pl --plugin=os::linux::snmp::plugin --mode=cpu --help
`


My configuration :
> Centreon Web version: 2.8.26
> Centreon Engine version: 1.8.1
> Centreon Broker version:
> centreon-pp-manager: 2.4.0
> centreon-license-manager: 1.1.0
> Pluggin :
> 
> centreon-plugin-Operatingsystems-Windows-Snmp-20180821-1
> centreon-plugin-Operatingsystems-Linux-Snmp-20180821-1

**Problem :**
/usr/lib/centreon/plugins/centreon_linux_snmp.pl --plugin=os::linux::snmp::plugin --mode=cpu --hostname=10.61.1.2 --snmp-version='2c' --snmp-community='public' --warning='80' --critical='90' Unknown option: warning at /usr/lib/centreon/plugins/centreon/plugins/alternative/Getopt.pm line 67.

**Comment by Sims24** [comment] 2018-10-22 12:20
Hi, 

Yes we did a break change allowing us tu define a cpu threshold for core or average.

Then treshold options are now : 

--warning-core / --critical-core 

or 

--warning-average / --critical-average 

Thanks

**Comment by cgagnaire** [comment] 2018-10-24 16:03
Hi @LLFT,
This break change comes with the 20180928 tag and is not yet released in the fatpacked versions.
So you shouldn't have the problem.
You must have cloned the project in the same directory as the fatpacked plugins. And you shoudn't do so.
Anyhow, @Sims24 forgot to update the helper :)

**Comment by cgagnaire** [comment] 2018-10-24 16:06
My mistake, @Sims24 did. I don't know why I doubted him. <3

**Closed by cgagnaire** 2018-10-24 16:06 UTC
