### ISSUE TITLE
Enhancement for interfaces: check if interface speed has changed

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-plugins#954] opened 2018-04-16 11:54 UTC
It would be very nice if you can extent the checks for interfaces and get an alert, if the speed of the interface has change (from 1Gb to 100Mb ecc.). This should be configured in the warning and critical options.
What do you think about it?

Jochen

**Comment by Sims24** [comment] 2018-04-16 13:14
Hi, 

yes I think this is a duplicate of https://github.com/centreon/centreon-plugins/issues/762 . 

we will think about it and see how tough it would be to implement.

**Closed** 2018-04-26 15:51 UTC
Labels: enhancement, mode
